# Generated by Django 3.1.5 on 2021-02-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210129_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pictures/default.jpg', upload_to='media/profile_pictures'),
        ),
    ]
