# Generated by Django 3.1.6 on 2021-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20210218_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
