# Generated by Django 3.1.6 on 2021-02-20 15:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210218_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
