# Generated by Django 3.1.6 on 2021-02-23 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0007_questiondownvote_questionupvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionUpVote',
            new_name='QuestionLike',
        ),
        migrations.DeleteModel(
            name='QuestionDownVote',
        ),
    ]
